### ISSUE TITLE
Audio event cuts off early/randomly

### ISSUE THREAD

**Issue by OutThisLife** [RetellAI/retell-client-js-sdk#1]
Sometimes while an agent is speaking, the audio buffer will stop prematurely. Feels like the event just closes itself randomly.

**Comment by weijia-yu** [comment]
Did you say anything or there is background noise? Your voice can interrupt the agent

**Comment by OutThisLife** [comment]
No, it happens mid stream.

**Comment by nick-braintrust** [comment]
@weijia-yu What Im seeing is the audio stream continue uninterrupted, but the audio data buffer get cut off.
https://github.com/RetellAI/retell-client-js-sdk/assets/163348886/3e948561-f8f1-44bb-8bcb-e6c0fc1b9485

**Comment by weijia-yu** [comment]
Cannot reproduce this error and will reopen if someone report again
