### ISSUE TITLE
Reverberated Voice in iOS Safari

### ISSUE THREAD

**Issue by levihatchmatter** [RetellAI/retell-client-js-sdk#18]
I tried the [https://github.com/RetellAI/retell-frontend-reactjs-demo](https://github.com/RetellAI/retell-frontend-reactjs-demo) in iOS Safari (simulator and real device) and the voice sounds reverberated. Sounds fine on Chrome and Safari in MacOS.

Agent: Single-Prompt Agent, Myra with default settings

I am also using `retell-client-js-sdk v2.0.3` in another project and have the same issue.

iOS 17.6.1
iPhone 14 Pro

**Update:**

It seems like what is happening is the mic is picking up the agent audio output and there's a feedback loop. If I turn up the volume the agent cuts out and tries responding to itself. I tried using the `.mute()` method but it didn't seem to make a difference.

```typescript
// When agent starts talking for the utterance
    // useful for animation
    retellWebClient.on("agent_start_talking", () => {
      console.log("agent_start_talking");
      retellWebClient.mute();
    });
    
    // When agent is done talking for the utterance
    // useful for animation
    retellWebClient.on("agent_stop_talking", () => {
      console.log("agent_stop_talking");
      retellWebClient.unmute();
    });
```

I've also confirmed this happens on the retellai.com dashboard when testing an agent.

**Comment by AustinZzx** [comment]
We have pushed a fix for this. Should be good now.
