### ISSUE TITLE
Receive function call results from client js sdk

### ISSUE THREAD

**Issue by spikecodes** [RetellAI/retell-client-js-sdk#5]
Is there a way to receive the JSON output on the client from calling a function? Let's say my retell python backend defines a function (which does something other than ending the call) that gets called by the LLM, how can I access the function from this JS SDK on the client?

**Comment by AustinZzx** [comment]
If you are using your custom LLM server, then you can use the metadata event to pass any data to your frontend: https://docs.retellai.com/api-references/llm-websocket#metadata-event

**Comment by spikecodes** [comment]
Great, thanks!
